# Generated by Django 4.0a1 on 2021-10-12 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShotGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название группы шотов')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_groups', to='projects.project')),
            ],
        ),
    ]
