# Generated by Django 4.0a1 on 2021-10-12 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('shots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название шота')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='users.user')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='shots.shotgroup')),
            ],
        ),
    ]
